import { Context, Markup } from 'telegraf';
import path from 'path';
import fs from 'fs';
import PDFDocument from 'pdfkit';
import logger from '../logger';
import {
  ConversationState,
  storeSession,
  getSession,
  setState,
  clearSession,
  storeResults,
  getResultsPage,
} from '../services/conversation';
import { searchParties, getVouchersByParty as fuzzyGetVouchers } from '../services/fuzzySearch';
import { formatDate, formatVoucherType, formatIndian } from '../utils/formatters';
import { escapeMd } from '../utils/formatters';

const VOUCHERS_PER_PAGE = 5;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build inline keyboard for party selection (max 5 per page). */
function partySelectionKeyboard(
  parties: Array<{ item: { id: number | string; party_name: string }; score: number }>,
): ReturnType<typeof Markup.inlineKeyboard> {
  const rows = parties.slice(0, 5).map((match) => {
    const partyName = match.item.party_name;
    return [Markup.button.callback(partyName, `inv_party:${partyName}`)];
  });

  // Show "no results" row if empty
  if (rows.length === 0) {
    rows.push([Markup.button.callback('❌ No parties found', 'noop')]);
  }

  rows.push([Markup.button.callback('🏠 Main Menu', 'start')]);
  return Markup.inlineKeyboard(rows);
}

/** Build voucher pagination keyboard. */
function voucherPaginationKeyboard(
  chatId: number,
  partyName: string,
  page: number,
  totalPages: number,
): ReturnType<typeof Markup.inlineKeyboard> {
  const rows: ReturnType<typeof Markup.button.callback>[][] = [];

  // Older / Newer buttons
  const navButtons: ReturnType<typeof Markup.button.callback>[] = [];
  if (page > 0) {
    navButtons.push(Markup.button.callback('⬅️ Older 5', `inv_page:${partyName}:${page - 1}`));
  }
  if (page < totalPages - 1) {
    navButtons.push(Markup.button.callback('➡️ Newer 5', `inv_page:${partyName}:${page + 1}`));
  }
  if (navButtons.length > 0) {
    rows.push(navButtons);
  }

  rows.push([Markup.button.callback('🔍 Search Other Party', 'invoice')]);
  rows.push([Markup.button.callback('🏠 Main Menu', 'start')]);
  return Markup.inlineKeyboard(rows);
}

/** Build format selection keyboard for a specific voucher. */
function formatSelectionKeyboard(voucherId: number | string): ReturnType<typeof Markup.inlineKeyboard> {
  return Markup.inlineKeyboard([
    [
      Markup.button.callback('📄 PDF', `inv_fmt_pdf:${voucherId}`),
      Markup.button.callback('📊 Excel', `inv_fmt_excel:${voucherId}`),
    ],
    [Markup.button.callback('🔙 Back to Vouchers', `inv_back:${voucherId}`)],
    [Markup.button.callback('🏠 Main Menu', 'start')],
  ]);
}

/** Generate a basic PDF invoice using pdfkit. */
async function generateInvoicePdf(
  voucher: any,
  outputPath: string,
): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = fs.createWriteStream(outputPath);

      doc.pipe(stream);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text('TallyOnMobile', { align: 'center' });
      doc.fontSize(12).font('Helvetica').text('Invoice / Voucher', { align: 'center' });
      doc.moveDown();

      // Horizontal rule
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown();

      // Voucher details
      doc.fontSize(11).font('Helvetica-Bold');
      doc.text(`Voucher #: `, { continued: true }).font('Helvetica').text(`${voucher.voucher_number || '—'}`);
      doc.font('Helvetica-Bold').text(`Date: `, { continued: true }).font('Helvetica').text(`${formatDate(voucher.voucher_date || voucher.date)}`);
      doc.font('Helvetica-Bold').text(`Type: `, { continued: true }).font('Helvetica').text(`${formatVoucherType(voucher.voucher_type)}`);
      doc.moveDown();

      // Party
      doc.font('Helvetica-Bold').text(`Party: `, { continued: true }).font('Helvetica').text(`${voucher.party_name || '—'}`);
      doc.moveDown();

      // Horizontal rule
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown();

      // Amount
      doc.fontSize(14).font('Helvetica-Bold');
      doc.text(`Amount: ${formatIndian(Number(voucher.amount) || 0)}`, { align: 'right' });
      doc.moveDown();

      // Footer
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown();
      doc.fontSize(9).font('Helvetica').text(
        'Generated by TallyOnMobile AI Bot • Powered by Nous Research',
        { align: 'center' },
      );

      doc.end();

      stream.on('finish', () => resolve());
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/**
 * /invoice command handler.
 * If a party name is provided inline, search and show matching parties.
 * Otherwise, ask for a party name.
 */
export async function invoiceCommand(ctx: Context): Promise<void> {
  const chatId = ctx.chat!.id;
  const text = ctx.message && 'text' in ctx.message ? ctx.message.text : '';
  const args = text.replace(/^\/invoice\s*/i, '').trim();

  if (args) {
    // Direct party query: /invoice <party>
    await searchAndShowParties(ctx, args);
  } else {
    // Ask for party name and set state
    setState(chatId, ConversationState.AWAITING_PARTY, { reportType: 'invoice' });
    await ctx.replyWithMarkdown(
      '🧾 *Invoice / Voucher Search*\n\nPlease enter a *party name* to search for invoices:',
      {
        reply_markup: {
          inline_keyboard: [
            [{ text: '🏠 Main Menu', callback_data: 'start' }],
          ],
        },
      },
    );
  }
}

/**
 * Search parties by name and show matching results as inline keyboard.
 */
export async function searchAndShowParties(
  ctx: Context,
  query: string,
): Promise<void> {
  const chatId = ctx.chat!.id;
  logger.info('Invoice: searching parties', { chatId, query });

  await ctx.replyWithMarkdown(`🔍 *Searching parties for:* \`${escapeMd(query)}\`…`);

  try {
    const matches = await searchParties(query, { maxResults: 10 });
    const parties = matches.slice(0, 5);

    // Store in session for later reference
    storeSession(chatId, {
      lastSearchedParty: query,
      lastResults: matches.map((m) => m.item),
      currentPage: 0,
      pageSize: VOUCHERS_PER_PAGE,
    });

    if (parties.length === 0) {
      await ctx.replyWithMarkdown(
        `❌ No parties found matching \`${query}\`.\n\nPlease try a different name.`,
        {
          reply_markup: {
            inline_keyboard: [
              [{ text: '🔍 Try Again', callback_data: 'invoice' }],
              [{ text: '🏠 Main Menu', callback_data: 'start' }],
            ],
          },
        },
      );
      return;
    }

    const partyLines = parties.map(
      (p, i) => `${i + 1}. ${escapeMd(p.item.party_name)} (${p.method}, score: ${p.score})`,
    );

    const msg = [
      `🧾 *Invoice Search*`,
      '',
      `Found *${matches.length}* match(es) for \`${query}\`:`,
      '',
      ...partyLines,
      '',
      'Select a party to view their recent vouchers 👇',
    ].join('\n');

    await ctx.replyWithMarkdown(msg, partySelectionKeyboard(parties));
  } catch (err: any) {
    logger.error('Invoice: party search error', { chatId, error: err?.message });
    await ctx.replyWithMarkdown(
      '⚠️ *Error searching parties.* Please try again later.',
    );
  }
}

/**
 * Handle party selection from inline keyboard.
 * Fetches last 5 vouchers for the selected party.
 */
export async function onPartySelected(ctx: Context, partyName: string): Promise<void> {
  const chatId = ctx.chat!.id;
  logger.info('Invoice: party selected', { chatId, partyName });

  storeSession(chatId, { lastSearchedParty: partyName });

  await ctx.replyWithMarkdown(`📄 *Fetching vouchers for* \`${partyName}\`…`);

  try {
    const vouchers = await fuzzyGetVouchers(partyName, { limit: 20 });
    storeResults(chatId, vouchers, { pageSize: VOUCHERS_PER_PAGE });

    if (vouchers.length === 0) {
      await ctx.replyWithMarkdown(
        `📭 No vouchers found for \`${partyName}\`.`,
        {
          reply_markup: {
            inline_keyboard: [
              [{ text: '🔍 Search Other Party', callback_data: 'invoice' }],
              [{ text: '🏠 Main Menu', callback_data: 'start' }],
            ],
          },
        },
      );
      return;
    }

    await showVoucherPage(ctx, chatId, 0);
  } catch (err: any) {
    logger.error('Invoice: fetch vouchers error', { chatId, error: err?.message });
    await ctx.replyWithMarkdown('⚠️ *Error fetching vouchers.* Please try again.');
  }
}

/**
 * Show a page of vouchers.
 */
async function showVoucherPage(ctx: Context, chatId: number, page: number): Promise<void> {
  const { items, page: currentPage, totalPages, totalResults } = getResultsPage(chatId, page);

  if (items.length === 0) {
    await ctx.replyWithMarkdown('📭 No vouchers to display.');
    return;
  }

  const session = getSession(chatId);
  const partyName = session.lastSearchedParty ?? 'Selected Party';

  const voucherLines = items.map((v: any, i: number) => {
    const idx = currentPage * VOUCHERS_PER_PAGE + i + 1;
    return [
      `${idx}. ${formatVoucherType(v.voucher_type)}`,
      `   📅 ${formatDate(v.voucher_date || v.date)}`,
      `   💰 ${formatIndian(Number(v.amount) || 0)}`,
      `   🆔 \`${v.voucher_number || '—'}\``,
    ].join('\n');
  });

  const msg = [
    `🧾 *Vouchers — ${partyName}*`,
    `📄 Page ${currentPage + 1} of ${totalPages} (${totalResults} total)`,
    '',
    '━━━━━━━━━━━━━━━━━━',
    ...voucherLines,
    '',
    'Select a voucher to download 👇',
  ].join('\n');

  // Build voucher selection keyboard
  const rows: ReturnType<typeof Markup.button.callback>[][] = items.map((v: any) => {
    const label = `${v.voucher_number || '#' + v.id} • ${formatIndian(Number(v.amount) || 0)}`;
    return [Markup.button.callback(label, `inv_vouch:${v.id}`)];
  });

  // Navigation
  const navButtons: ReturnType<typeof Markup.button.callback>[] = [];
  if (currentPage > 0) {
    navButtons.push(Markup.button.callback('⬅️ Older 5', `inv_page:${partyName}:${currentPage - 1}`));
  }
  if (currentPage < totalPages - 1) {
    navButtons.push(Markup.button.callback('➡️ Newer 5', `inv_page:${partyName}:${currentPage + 1}`));
  }
  if (navButtons.length > 0) {
    rows.push(navButtons);
  }

  rows.push([Markup.button.callback('🔍 Search Other Party', 'invoice')]);
  rows.push([Markup.button.callback('🏠 Main Menu', 'start')]);

  await ctx.replyWithMarkdown(msg, Markup.inlineKeyboard(rows));
}

/**
 * Handle voucher pagination.
 */
export async function onVoucherPage(
  ctx: Context,
  partyName: string,
  page: number,
): Promise<void> {
  const chatId = ctx.chat!.id;
  storeSession(chatId, { lastSearchedParty: partyName });
  await showVoucherPage(ctx, chatId, page);
}

/**
 * Handle voucher selection – ask format (PDF or Excel).
 */
export async function onVoucherSelected(ctx: Context, voucherId: string): Promise<void> {
  const chatId = ctx.chat!.id;

  // Store selected voucher ID in session
  setState(chatId, ConversationState.AWAITING_FORMAT, {
    lastSearchedVoucher: voucherId,
  });

  // Try to fetch the voucher from stored results
  const session = getSession(chatId);
  const results = session.lastResults ?? [];
  const voucher = results.find((v: any) => String(v.id) === String(voucherId));

  if (!voucher) {
    await ctx.replyWithMarkdown('⚠️ *Voucher data not found.* Please search again.');
    return;
  }

  const msg = [
    `📄 *Voucher Selected*`,
    '',
    `🧾 Voucher #: \`${voucher.voucher_number || '—'}\``,
    `📅 Date: ${formatDate(voucher.voucher_date || voucher.date)}`,
    `💳 Type: ${formatVoucherType(voucher.voucher_type)}`,
    `💰 Amount: ${formatIndian(Number(voucher.amount) || 0)}`,
    '',
    'Choose a format to download 👇',
  ].join('\n');

  await ctx.replyWithMarkdown(msg, formatSelectionKeyboard(voucherId));
}

/**
 * Generate and send PDF for a selected voucher.
 */
export async function onGeneratePdf(ctx: Context, voucherId: string): Promise<void> {
  const chatId = ctx.chat!.id;
  const session = getSession(chatId);
  const results = session.lastResults ?? [];
  const voucher = results.find((v: any) => String(v.id) === String(voucherId));

  if (!voucher) {
    await ctx.replyWithMarkdown('⚠️ *Voucher not found.* Please search again.');
    return;
  }

  await ctx.replyWithMarkdown('📄 *Generating PDF…* Please wait ⏳');

  try {
    const fileName = `invoice_${voucher.voucher_number || voucher.id}_${Date.now()}.pdf`;
    const outputDir = path.resolve(__dirname, '..', '..', 'temp');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    const outputPath = path.join(outputDir, fileName);

    await generateInvoicePdf(voucher, outputPath);

    // Send the PDF
    await ctx.replyWithDocument(
      { source: outputPath, filename: fileName },
      {
        caption: [
          `🧾 *Invoice: ${voucher.voucher_number || '—'}*`,
          `📅 ${formatDate(voucher.voucher_date || voucher.date)}`,
          `💰 ${formatIndian(Number(voucher.amount) || 0)}`,
        ].join('\n'),
        parse_mode: 'Markdown',
      },
    );

    // Cleanup temp file
    fs.unlink(outputPath, (err) => {
      if (err) logger.warn('Failed to delete temp PDF', { path: outputPath, error: err.message });
    });

    // Return to voucher list
    await showVoucherPage(ctx, chatId, session.currentPage ?? 0);
  } catch (err: any) {
    logger.error('Invoice: PDF generation error', { chatId, error: err?.message });
    await ctx.replyWithMarkdown('⚠️ *Error generating PDF.* Please try again.');
  }
}

/**
 * Handle format generation (Excel placeholder – shows message that Excel is coming soon).
 */
export async function onGenerateExcel(ctx: Context, voucherId: string): Promise<void> {
  await ctx.replyWithMarkdown(
    '📊 *Excel export is coming soon!*\n\nPlease select 📄 PDF for now.',
  );
}

/**
 * Handle the "back to vouchers" action.
 */
export async function onBackToVouchers(ctx: Context): Promise<void> {
  const chatId = ctx.chat!.id;
  const session = getSession(chatId);
  const partyName = session.lastSearchedParty;
  if (partyName) {
    await onPartySelected(ctx, partyName);
  } else {
    await invoiceCommand(ctx);
  }
}
